name: twobody

channels:
    - astropy

dependencies:
    - python=3
    # - astropy
    - Cython
    - matplotlib
    - numpy
    - pip:
        - git+https://github.com/adrn/astropy.git@coordinates/skyoffset
