[build-system]

requires = ["setuptools",
            "setuptools_scm",
            "wheel",
            "extension-helpers",
	    "numpy",
            "cython"]

build-backend = 'setuptools.build_meta'
