name: Test twobody
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 12 * * 1"  # Mondays @ 8AM Eastern

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:

          - name: Python 3.10 standard tests
            os: ubuntu-latest
            python: '3.10'
            toxenv: py310-test

          - name: Python 3.11 standard tests
            os: ubuntu-latest
            python: '3.11'
            toxenv: py311-test

          - name: Python 3.12 standard tests
            os: ubuntu-latest
            python: '3.12'
            toxenv: py312-test

          - name: Python 3.11 dev dependencies
            os: ubuntu-latest
            python: '3.11'
            toxenv: py311-test-devdeps
            toxposargs: --durations=50

          # Mac and Windows:
          - name: Python 3.11 standard tests (macOS)
            os: macos-latest
            python: '3.11'
            toxenv: py311-test

          - name: Python 3.11 standard tests (Windows)
            os: windows-latest
            python: '3.11'
            toxenv: py311-test

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        if: "!startsWith(matrix.os, 'windows')"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      # Windows:
      - uses: conda-incubator/setup-miniconda@v3
        if: startsWith(matrix.os, 'windows')
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies - Windows
        if: startsWith(matrix.os, 'windows')
        shell: bash -l {0}
        run: |
          conda install -c conda-forge -q libpython
          python -m pip install -e .[test]
          python -m pip install tox

      - name: Run tests - Windows
        if: startsWith(matrix.os, 'windows')
        shell: bash -l {0}
        run: |
          tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} ${{ matrix.toxposargs }}

      # Any *nix:
      - name: Install Python dependencies - nix
        if: "!startsWith(matrix.os, 'windows')"
        run: python -m pip install --upgrade tox

      - name: Run tests - nix
        if: "!startsWith(matrix.os, 'windows')"
        run: tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
